name: feren-os-theme # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2021.04.0.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: The official Feren OS Style. # 79 char long summary
description: |
  The official Feren OS Style, now available for your Snap applications.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

slots:
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/feren
        - $SNAP/share/gtk2/feren-dark
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/feren
        - $SNAP/share/themes/feren-dark
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Inspire
        - "$SNAP/share/icons/Inspire Dark"
        
parts:
  feren-theme:
    # See 'snapcraft plugins'
    after: [utils]
    plugin: nil
    source: https://github.com/feren-OS/feren-theme.git
    source-branch: universalpkg
    source-type: git
    build-packages:
      - libcanberra-gtk-module
      - libglib2.0-dev
      - git-lfs
    override-build: |
        snapcraftctl build
        snapcraftctl set-version "$(git describe --tags 2>/dev/null || echo 1.0)"
        echo src $SNAPCRAFT_PART_SRC
        export | grep SNAPCRAFT
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
        mv ./* $SNAPCRAFT_PART_INSTALL/share/themes/
        $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
    stage:
      - share/gtk2/*/gtk-2.0
      - share/themes/*/gtk-3*

    # icon theme
  inspire-icon-theme:
    after: [utils]
    plugin: nil
    source: https://github.com/feren-OS/Inspire-Icon-Theme.git
    source-type: git 
    override-build: |
        snapcraftctl build
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
        mv ./* $SNAPCRAFT_PART_INSTALL/share/icons/
        $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/Inspire
      - "share/icons/Inspire Dark"


  utils:
    plugin: dump
    source: utils
    prime:
      - .*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
